In [1]:
import torch

In [32]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [33]:
Q = 3*a**3 - b**2

In [34]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [35]:
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


In [36]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 # - b**2
Q.sum().backward()

In [37]:
print(9*a**2 == a.grad)
print(-2*b == b.grad)
print(a.grad)

tensor([True, True])
False
tensor([36., 81.])


In [41]:
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.a = torch.nn.Parameter(torch.tensor([2., 3.]), requires_grad=True)
    
    def forward(self):
        return self.a[0]

In [42]:
model = Model()
loss = 3*model()**3
loss.backward()
print(model.a.grad)

tensor([36.,  0.])
